version: "3.9"

services:
  referee:
    build:
      context: .
      dockerfile: flet_app/Dockerfile
    image: ai-basketball-referee:latest
    container_name: ai-referee
    ports:
      - "8081:8081"
    environment:
      # VIDEO_SOURCE can be 0 (default camera, Linux only), a file path inside the container,
      # or a network/RTSP stream URL.
      - VIDEO_SOURCE=${VIDEO_SOURCE:-0}
      - DEVICE=${DEVICE:-CPU}
      - RULES=${RULES:-FIBA}
    volumes:
      # Mount models and assets read-only; adjust paths as needed
      - ./models:/app/models:ro
      - ./flet_app/assets:/app/flet_app/assets:ro
      # To run with a local video file, also mount it and set VIDEO_SOURCE to that path, e.g. /app/videos/clip.mp4
      # - ./videos:/app/videos:ro

    # Linux-only: enable webcam passthrough (uncomment below). Not supported on macOS/Windows Docker Desktop.
    # devices:
    #   - "/dev/video0:/dev/video0"
    # privileged: true

    # Always restart unless stopped
    restart: unless-stopped
